language: r
cache: packages
dist: trusty
sudo: true
warnings_are_error: true

## to install rstan it seems like you need quite a lot
# of configuration scaffolding.
# This is cribbed from the rstan github.
# Congifures clang as the cxx complier.
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir ./rstan
  - eval "CXX14 = $CXX"
  - echo "CXX = $CXX" >> ./rstan/R_Makevars
  - echo "CXX14 = $CXX" >> ./rstan/R_Makevars
  - echo "CXX14FLAGS = `R CMD config CXXFLAGS` -pedantic -g0 -fPIC" >> ./rstan/R_Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX =~ clang.* ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - echo ${CXX} --version
  - echo ${CLANG_EXTRA_ARG}
  # - more ./rstan/R_Makevars
  - mkdir -p ~/.R/; cat ./rstan/R_Makevars > ~/.R/Makevars
